theme: jekyll-theme-minimal
title: Mattia Merenda
descrition: Personal homepage of Mattia Merenda
author: Mattia Merenda
logo: profile.jpg

mail-work: saveriomattia.merenda@studenti.unipr.it
linkedin: https://www.linkedin.com/in/merendamattia/
# scholar:
# research-gate: 
orcid: https://orcid.org/0009-0000-4137-9852
# researcherid: 
# scopus: 
github: https://github.com/merendamattia
# dblp: 

exclude: [README.md]
future: true

url: "https://www.merendamattia.com/"
plugins:
  - jekyll-sitemap

