theme: jekyll-theme-minimal
title: Mattia Merenda
descrition: Personal homepage of Mattia Merenda
author: Mattia Merenda
logo: profile.jpg

mail-work: saveriomattia.merenda@studenti.unipr.it
linkedin: https://www.linkedin.com/in/merendamattia/
# scholar:
# research-gate: 
# orcid: 
# researcherid: 
# scopus: 
github: https://github.com/merendamattia
# dblp: 

exclude: [README.md]
future: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

